import React, { useState } from 'react';
import { View, StyleSheet, ScrollView } from 'react-native';
import { Button, Text, Card } from 'react-native-paper';
import { auth, firestore } from '../firebase';
import { collection, doc, setDoc, getDocs, deleteDoc } from 'firebase/firestore';

const retos = [
  {
    id: 'habit01',
    title: 'Beber agua',
    challenge: 'Bebe al menos 8 vasos de agua hoy.',
    category: 'Salud',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit02',
    title: 'Caminar 10.000 pasos',
    challenge: 'Camina al menos 10.000 pasos durante el día.',
    category: 'Ejercicio',
    duration: '60 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1526403221961-142e1d0349f1?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit03',
    title: 'Meditar',
    challenge: 'Medita durante al menos 10 minutos.',
    category: 'Mental',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1508672019048-805c876b67e2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit04',
    title: 'Leer un libro',
    challenge: 'Lee al menos 10 páginas hoy.',
    category: 'Conocimiento',
    duration: '30 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit05',
    title: 'Escribir en un diario',
    challenge: 'Reflexiona sobre tu día y escribe en tu diario.',
    category: 'Mental',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit06',
    title: 'Estiramientos matutinos',
    challenge: 'Haz una rutina de estiramientos al despertar.',
    category: 'Ejercicio',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1554284126-5a1d4c9e59c6?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit07',
    title: 'No mirar el móvil al despertar',
    challenge: 'Evita usar el móvil durante la primera hora del día.',
    category: 'Bienestar',
    duration: '60 min',
    difficulty: 'Difícil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1523473827539-76007cf34e4a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit08',
    title: 'Cocinar una comida saludable',
    challenge: 'Prepara tú mismo una comida saludable.',
    category: 'Nutrición',
    duration: '45 min',
    difficulty: 'Media',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit09',
    title: 'Salir al sol',
    challenge: 'Toma al menos 15 minutos de sol hoy.',
    category: 'Salud',
    duration: '15 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit10',
    title: 'Evitar el azúcar',
    challenge: 'Evita el azúcar procesado durante el día.',
    category: 'Nutrición',
    duration: 'Todo el día',
    difficulty: 'Difícil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit11',
    title: 'Dormir 8 horas',
    challenge: 'Asegúrate de dormir al menos 8 horas.',
    category: 'Salud',
    duration: '8 h',
    difficulty: 'Media',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1519710164239-da123dc03ef4?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit12',
    title: 'Desayuno saludable',
    challenge: 'Empieza el día con un desayuno nutritivo.',
    category: 'Nutrición',
    duration: '15 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1498837167922-ddd27525d352?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit13',
    title: 'Agradecer 3 cosas',
    challenge: 'Escribe 3 cosas por las que estés agradecido hoy.',
    category: 'Mental',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit14',
    title: 'No redes sociales',
    challenge: 'Evita redes sociales por 24h.',
    category: 'Bienestar',
    duration: '24 h',
    difficulty: 'Difícil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit15',
    title: 'Hacer limpieza',
    challenge: 'Limpia una parte de tu casa durante 15 minutos.',
    category: 'Organización',
    duration: '15 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit16',
    title: 'No quejarse en todo el día',
    challenge: 'Evita quejarte por cualquier cosa hoy.',
    category: 'Mental',
    duration: '24 h',
    difficulty: 'Difícil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit17',
    title: 'Tomar descanso',
    challenge: 'Tómate 30 minutos para descansar sin pantallas.',
    category: 'Bienestar',
    duration: '30 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit18',
    title: 'Aprender algo nuevo',
    challenge: 'Dedica 20 minutos a aprender algo nuevo.',
    category: 'Conocimiento',
    duration: '20 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit19',
    title: 'Preparar la ropa',
    challenge: 'Deja lista la ropa para mañana.',
    category: 'Organización',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1521334884684-d80222895322?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit20',
    title: 'Sonreír más',
    challenge: 'Sonríe al menos 10 veces durante el día.',
    category: 'Mental',
    duration: 'Todo el día',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1508214751196-bcfd4ca60f91?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit21',
    title: 'Organizar el escritorio',
    challenge: 'Ordena tu espacio de trabajo.',
    category: 'Organización',
    duration: '15 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit22',
    title: 'Desconectar pantallas',
    challenge: 'Evita pantallas 1 hora antes de dormir.',
    category: 'Bienestar',
    duration: '1 h',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit23',
    title: 'Practicar gratitud',
    challenge: 'Escribe una cosa por la que estés agradecido.',
    category: 'Mental',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit24',
    title: 'Hacer una llamada a un amigo',
    challenge: 'Contacta con un amigo o familiar.',
    category: 'Social',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1511609814928-6654aaef9319?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit25',
    title: 'Planificar el día siguiente',
    challenge: 'Escribe tus tareas para mañana.',
    category: 'Organización',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit26',
    title: 'Practicar respiración profunda',
    challenge: 'Haz 5 minutos de respiraciones profundas.',
    category: 'Bienestar',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit27',
    title: 'Escribir metas semanales',
    challenge: 'Define 3 metas para la semana.',
    category: 'Organización',
    duration: '15 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1496317556649-f930d733eea2?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit28',
    title: 'Cenar temprano',
    challenge: 'Cena al menos 2 horas antes de dormir.',
    category: 'Salud',
    duration: 'N/A',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1525755662778-989d0524087e?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit29',
    title: 'Hacer ejercicio de fuerza',
    challenge: 'Realiza 30 minutos de entrenamiento de fuerza.',
    category: 'Ejercicio',
    duration: '30 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1554284126-5a1d4c9e59c6?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit30',
    title: 'Reducir cafeína',
    challenge: 'Limita la cafeína a una taza al día.',
    category: 'Salud',
    duration: 'Todo el día',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit31',
    title: 'Leer un artículo interesante',
    challenge: 'Lee un artículo sobre un tema que te guste.',
    category: 'Conocimiento',
    duration: '15 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit32',
    title: 'Desconectar de dispositivos',
    challenge: 'Apaga todos los dispositivos 1 hora antes de dormir.',
    category: 'Bienestar',
    duration: '1 h',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit33',
    title: 'Cuidar la postura',
    challenge: 'Presta atención a tu postura durante el día.',
    category: 'Salud',
    duration: 'Todo el día',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1523473827539-76007cf34e4a?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit34',
    title: 'Comer frutas',
    challenge: 'Come al menos 2 piezas de fruta.',
    category: 'Nutrición',
    duration: 'N/A',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit35',
    title: 'Hacer una tarea pendiente',
    challenge: 'Realiza una tarea que has estado posponiendo.',
    category: 'Organización',
    duration: '30 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1498804103079-a6351b050096?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit36',
    title: 'Evitar comida rápida',
    challenge: 'No consumas comida rápida hoy.',
    category: 'Nutrición',
    duration: 'Todo el día',
    difficulty: 'Difícil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1469474968028-56623f2fd55f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit37',
    title: 'Escribir un agradecimiento',
    challenge: 'Envía un mensaje agradeciendo a alguien.',
    category: 'Social',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit38',
    title: 'Probar un nuevo hobby',
    challenge: 'Dedica 30 minutos a un hobby nuevo.',
    category: 'Conocimiento',
    duration: '30 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit39',
    title: 'Planificar las comidas',
    challenge: 'Organiza tus comidas de la semana.',
    category: 'Organización',
    duration: '20 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1502741338009-cac2772e18bc?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit40',
    title: 'Escuchar música relajante',
    challenge: 'Escucha 20 minutos de música para relajarte.',
    category: 'Bienestar',
    duration: '20 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit41',
    title: 'Beber té verde',
    challenge: 'Toma una taza de té verde durante el día.',
    category: 'Salud',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1514361892635-df24952e1725?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit42',
    title: 'Hacer un acto de bondad',
    challenge: 'Haz algo amable por alguien.',
    category: 'Social',
    duration: '15 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit43',
    title: 'Limpiar el escritorio',
    challenge: 'Organiza y limpia tu área de trabajo.',
    category: 'Organización',
    duration: '20 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1519222970733-f546218fa6d7?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit44',
    title: 'Probar una receta saludable',
    challenge: 'Cocina una receta nueva y saludable.',
    category: 'Nutrición',
    duration: '40 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1466637574441-749b8f19452f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit45',
    title: 'Meditar al aire libre',
    challenge: 'Haz una meditación de 10 minutos fuera de casa.',
    category: 'Bienestar',
    duration: '10 min',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit46',
    title: 'Tomar agua con limón',
    challenge: 'Bebe un vaso de agua con limón en ayunas.',
    category: 'Salud',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit47',
    title: 'Escribir un diario',
    challenge: 'Escribe 5 minutos sobre tu día.',
    category: 'Bienestar',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit48',
    title: 'Practicar estiramientos',
    challenge: 'Realiza estiramientos durante 10 minutos.',
    category: 'Ejercicio',
    duration: '10 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1515377905703-c4788e51af15?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit49',
    title: 'Dormir 8 horas',
    challenge: 'Duerme al menos 8 horas esta noche.',
    category: 'Salud',
    duration: 'N/A',
    difficulty: 'Medio',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'habit50',
    title: 'Aprender una palabra nueva',
    challenge: 'Busca y aprende una palabra nueva hoy.',
    category: 'Conocimiento',
    duration: '5 min',
    difficulty: 'Fácil',
    date: new Date().toISOString().slice(0, 10),
    completed: false,
    image: 'https://images.unsplash.com/photo-1516251193007-45ef944ab0c6?auto=format&fit=crop&w=800&q=80',
  },
]



const subirRetos = async () => {
  try {
    for (const reto of retos) {
      await setDoc(doc(firestore, 'dailyChallengesTemplates', reto.id), reto);
    }
    alert('Retos subidos con éxito 🚀');
  } catch (error) {
    console.error('Error al subir retos:', error);
    alert('Error al subir retos');
  }
};

export default function SubirRetosScreen() {
  return (
    <ScrollView contentContainerStyle={styles.container}>
      <Text style={styles.title}>Subir Retos a Firebase</Text>
      {retos.map((reto) => (
        <Card key={reto.id} style={styles.card}>
          <Card.Cover source={{ uri: reto.image }} />
          <Card.Title title={reto.title} />
          <Card.Content>
            <Text>{reto.challenge}</Text>
          </Card.Content>
        </Card>
      ))}
      <Button
        mode="contained"
        onPress={subirRetos}
        style={styles.button}
        labelStyle={{ fontWeight: 'bold' }}
      >
        Subir retos a Firebase
      </Button>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  container: {
    padding: 20,
    backgroundColor: '#fafafb',
  },
  title: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 20,
    color: '#36a2c1',
  },
  card: {
    marginBottom: 16,
    borderRadius: 12,
    overflow: 'hidden',
  },
  button: {
    marginTop: 20,
    backgroundColor: '#36a2c1',
  },
});
